name: redux_toolkit
description: Dart port of the official, opinionated, batteries-included toolset
  for efficient Redux development
version: 0.1.1
homepage: https://github.com/mrnkr/redux_toolkit

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  redux: ^4.0.0+2
  reselect: ^0.4.0
  redux_thunk: ^0.3.0
  redux_dev_tools: ^0.5.2
  redux_remote_devtools: ^2.0.0
  meta: '>=1.1.8 <=1.2.2'

dev_dependencies:
  test: ^1.3.0
  mockito: ^4.1.1
  pedantic: ^1.9.0

